---
# Configure Applications

# - name: enable  service
#   systemd:
#     name:
#     enabled: yes
#   when:
#   - _user is defined
#   - _group is defined
#   - _enabled == true

- name: reload systemd deamon
  systemd:
    daemon_reload: yes

