---
# - name: download
#   get_url:
#     url: "{{ _download_url }}"
#     dest: "{{_download_dest }}"
#     mode: u=rw,g=r,o=r
#     timeout: 600
#     validate_certs: false
#   register: download_
#   when: _download_url is defined

