---
# Add Server Manager Channels
- name: Repos
  debug:
    msg: "Processing Repos"
# Clean Cache First Before Adding Channels and Repos
# Clean yum cache
- name: Clean yum cache
  command: yum clean all
  when:
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "OracleLinux"

# Clean dnf cache
- name: Clean dnf cache
  command: dnf clean all
  when:
    - ansible_distribution_major_version == "8"
    - ansible_distribution == "OracleLinux"

# Clean dnf cache
- name: Clean dnf cache
  command: dnf clean all
  when:
    - ansible_distribution_major_version == "9"
    - ansible_distribution == "OracleLinux"

# Add Server Manager Erlang Channel
- name: Add Server Manager Channel
  command: rhn-channel -u ol-svrmgr -p ol-svrmgr -a -c erlang-ol7_x86_64_latest
  when:
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "OracleLinux"
    - add_channel == true

- name: Add Server Manager Channel
  command: rhn-channel -u ol-svrmgr -p ol-svrmgr -a -c erlang-ol8_x86_64_latest
  when:
    - ansible_distribution_major_version == "8"
    - ansible_distribution == "OracleLinux"
    - add_channel == true

- name: Add Server Manager Channel
  command: rhn-channel -u ol-svrmgr -p ol-svrmgr -a -c erlang-ol9_x86_64_latest
  when:
    - ansible_distribution_major_version == "9"
    - ansible_distribution == "OracleLinux"
    - add_channel == true

# Add Server Manager RabbitMQ Channel
- name: Add Server Manager Channel
  command: rhn-channel -u ol-svrmgr -p ol-svrmgr -a -c rabbitmq-ol7_x86_64_latest
  when:
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "OracleLinux"
    - add_channel == true

- name: Add Server Manager Channel
  command: rhn-channel -u ol-svrmgr -p ol-svrmgr -a -c rabbitmq-ol8_x86_64_latest
  when:
    - ansible_distribution_major_version == "8"
    - ansible_distribution == "OracleLinux"
    - add_channel == true

- name: Add Server Manager Channel
  command: rhn-channel -u ol-svrmgr -p ol-svrmgr -a -c rabbitmq-ol9_x86_64_latest
  when:
    - ansible_distribution_major_version == "9"
    - ansible_distribution == "OracleLinux"
    - add_channel == true


# Refresh the cache...
# Update yum cache
- name: Update yum cache
  command: yum makecache
  when:
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "OracleLinux"
    - add_channel == true or add_optional_channel == true or add_repo == true

# update dnf cache
- name: Update dnf cache
  command: dnf makecache
  when:
    - ansible_distribution_major_version == "8"
    - ansible_distribution == "OracleLinux"
    - add_channel == true or add_optional_channel == true or add_repo == true

# update dnf cache
- name: Update dnf cache
  command: dnf makecache
  when:
    - ansible_distribution_major_version == "9"
    - ansible_distribution == "OracleLinux"
    - add_channel == true or add_optional_channel == true or add_repo == true

# REMOVE SERVER MANAGER CHANNELS AND REPOS  IF THEY EXIST
# Remove Server Manager Channel
- name: Remove Server Manager Channel
  command: rhn-channel -u ol-svrmgr -p ol-svrmgr -r ol7_x86_64_latest
  when:
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "OracleLinux"
    - remove_channel == true

# Remove Repo
- name: Remove Server Manager Repo
  command: rm -f /etc/yum.repos.d/ol7-svrmgr.repo
  when:
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "OracleLinux"
    - remove_repo == true

# Allways Clean Cache After Removing Channels and Repos to avoid conflicts.
# Clean yum cache
- name: Clean yum cache
  command: yum clean all
  when:
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "OracleLinux"
    - remove_channel == true or remove_repo == true

# Clean dnf cache
- name: Clean dnf cache
  command: dnf clean all
  when:
    - ansible_distribution_major_version == "8"
    - ansible_distribution == "OracleLinux"
    - remove_channel == true or remove_repo == true

# Clean dnf cache
- name: Clean dnf cache
  command: dnf clean all
  when:
    - ansible_distribution_major_version == "9"
    - ansible_distribution == "OracleLinux"
    - remove_channel == true or remove_repo == true
