---
# Add Firewall Rules
- name: Rabbitmq Firewall Rules
  tags: rabbitmq_firewall
  template:
    src: files/rabbitmq-fire-rule.xml
    dest: /usr/lib/firewalld/services/rabbitmq.xml
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: u=rw,g=r,o=r
    backup: true
  when:
    rabbitmq_firewall == true


# Reload the firewalld service
- name: reload firewalld
  tags: reload_firewalld
  service:
    name: firewalld
    state: reloaded
    enabled: true

# Acctivate the firewalld service
- name: acctivate firewall rule
  command: firewall-cmd --add-service=rabbitmq --permanent
  when:
    rabbitmq_firewall == true

# Restart the firewalld service
- name: restart firewalld
  tags: restart_firewalld
  service:
    name: firewalld
    state: restarted
    enabled: true

- name: Services
  debug:
    msg: "Processing Services"
# Add Services
# - name: file
#   template:
#     src: templates/.service.j2
#     dest: "/etc/systemd/system/.service"
#     owner: root
#     group: root
#     mode: u=rw,g=r,o=r
#     backup:
#   when:
#   - _user is defined
#   - _group is defined
#   - _enabled == true

# Reload Systemd to pick up new config files
- name: reload systemd deamon
  systemd:
    daemon_reload: true

# Enable Services
- name: enable service
  systemd:
    name: rabbitmq-server
    enabled: true
  when:
    - rabbitmq_user is defined
    - rabbitmq_group is defined
    - rabbitmq_enabled == true

# Start Services
- name: start service
  systemd:
    name: rabbitmq-server
    state: started
    enabled: true
  when:
    - rabbitmq_user is defined
    - rabbitmq_group is defined
    - rabbitmq_enabled == true
