---
# Add Firewall Rules
- name: Firewall
  debug:
    msg: "Processing Firewall Rules"
# Update the firewall rules
- name: reload firewalld deamon
  tags: reload_firewalld
  systemd:
    name: firewalld
    daemon_reload: true
    enabled: true

# Restart the firewalld service
- name: restart firewalld
  tags: restart_firewalld
  service:
    name: firewalld
    state: restarted
    enabled: true

- name: Services
  debug:
    msg: "Processing Services"
# Add Services
# - name: file
#   template:
#     src: templates/.service.j2
#     dest: "/etc/systemd/system/.service"
#     owner: root
#     group: root
#     mode: u=rw,g=r,o=r
#     backup:
#   when:
#   - _user is defined
#   - _group is defined
#   - _enabled == true

# Reload Systemd to pick up new config files
- name: reload systemd deamon
  systemd:
    daemon_reload: true

# Enable Services
- name: enable service
  systemd:
    name: rabbitmq-server
    enabled: yes
  when:
  - rabbitmq_user is defined
  - rabbitmq_group is defined
  - rabbitmq_enabled == true

# Start Services
- name: start service
  systemd:
    name: rabbitmq-server
    state: started
  when:
  - rabbitmq_user is defined
  - rabbitmq_group is defined
  - rabbitmq_started == true

# Status of the Service
- name: status of the service
  systemd:
    name: rabbitmq-server
    state: status
  when:
  - rabbitmq_user is defined
  - rabbitmq_group is defined
  - rabbitmq_status == true
