# .bashrc

# User specific aliases and functions
# test
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias hg='history | grep'
alias h='history'
alias ll='ls -l'
alias la='ls -a'
alias l='ls -CF'
alias vi='vim'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias c='clear'
alias s='screen -x'
alias tmux='tmux -2'
alias p='ps -ef | grep'
alias t='tail -f'


# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi
set -o vi
PS1="\[\e[;91m\][\u@\h \W]\$ \[\e[m\]"

shopt -s histappend histreedit histverify
shopt -s no_empty_cmd_completion
export HISTCONTROL=ignoreboth:erasedups
export HISTTIMEFORMAT="%Y-%m-%d:%T:-> "
export HISTIGNORE="pwd:bg:fg:history"
export HISTFILE=$HOME/.bash_history
export HISTFILESIZE=1000000000
export HISTSIZE=10000000

