---
- name: append kerberos info to core-site.xml
  blockinfile:
    block: "{{lookup('file', 'templates/kerberos-core-site.xmlk2')}}"
    dest: /etc/hadoop/conf/core-site.xml
    insertbefore: '</configuration>'
    backup: true

- name: append kerberos info to hdfs-site.xml
  blockinfile:
    block: "{{lookup('file', 'templates/kerberos-hdfs-site.xml.j2')}}"
    dest: /etc/hadoop/conf/hdfs-site.xml
    insertbefore: '</configuration>'
    backup: true

- name: append kerberos info to yarn-site.xml
  blockinfile:
    block: "{{lookup('file', 'templates/kerbersos-yarn-site.xml.j2')}}"
    dest: /etc/hadoop/conf/yarn-site.xml
    insertbefore: '</configuration>'
    backup: true
