---
# Start Resource Manager
- name: "Checking if  Resorce Manager service already running"
  command: "jps"
  become: true
  become_user: root
  ignore_errors: true
  changed_when: false
  register: hadoop_resourcemanager_service_check

- name: "Start Resource Manager"
  command: "yarn --deamon start resourcemanager"
  become: true
  become_user: yarn
  changed_when: false
  when: hadoop_resourcemanager_service_check.stdout |
    regex_search('(ResourceManager)') != "ResourceManager"
