//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

# Version 1.0
# Pinot Role
pinot.service.role=SERVER
# Pinot Cluster name, set to relevent enviroment name
pinot.cluster.name=development
# Pinot Zookeeper Server, add all zookeepers here host:port,host:port ...
pinot.zk.server=zookafka:2181
# Use hostname as Pinot Instance ID other than IP
pinot.set.instance.id.to.hostname=true
# Pinot Server Netty Port for queris
pinot.server.netty.port=8098
# Pinot Server Admin API port
pinot.server.adminapi.port=8097
# Pinot Server Data Directory
pinot.server.instance.dataDir=/pinot/data/server/index
# Pinot Server Temporary Segment Tar Directory
pinot.server.instance.segmentTarDir=/pinot/data/server/segmentTar
# This is the default, 10 minutes.
pinot.server.startup.timeoutMs=600000
# Enable Service Status Check
pinot.server.startup.enableServiceStatusCheck=true
# The default is 0, and the server will not wait
pinot.server.starter.realtimeConsumptionCatchupWaitMs=60000
# This is disabled by default.
pinot.server.starter.enableRealtimeOffsetBasedConsumptionStatusChecker=true
# the default is 10000. Values <=0 are not allowed.
pinot.server.starter.realtimeConsumptionCatchupWaitMs=10000
# Enable stream download and untar
pinot.server.instance.segment.stream.download.untar=true
# The max download-untar rate is limited to 100000000 bytes/sec
pinot.server.instance.segment.stream.download.untar.rate.limit.bytes.per.sec=100000000

