---
# Add Server Manager Channels
- name: Repos
  debug:
    msg: "Processing Repos"
# Clean Cache First Before Adding Channels and Repos
# Clean yum cache
- name: Clean yum cache
  command: yum clean all
  when:
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "OracleLinux"

# Clean dnf cache
- name: Clean dnf cache
  command: dnf clean all
  when:
    - ansible_distribution_major_version == "8"
    - ansible_distribution == "OracleLinux"

# Clean dnf cache
- name: Clean dnf cache
  command: dnf clean all
  when:
    - ansible_distribution_major_version == "9"
    - ansible_distribution == "OracleLinux"

# Add Server Manager Defualt Channel
- name: Add Server Manager Channel
  command: rhn-channel -u ol-svrmgr -p ol-svrmgr -a -c ol7_x86_64_latest
  when:
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "OracleLinux"
    - add_channel == true

- name: Add Server Manager Channel
  command: rhn-channel -u ol-svrmgr -p ol-svrmgr -a -c ol8_x86_64_latest
  when:
    - ansible_distribution_major_version == "8"
    - ansible_distribution == "OracleLinux"
    - add_channel == true

- name: Add Server Manager Channel
  command: rhn-channel -u ol-svrmgr -p ol-svrmgr -a -c ol9_x86_64_latest
  when:
    - ansible_distribution_major_version == "9"
    - ansible_distribution == "OracleLinux"
    - add_channel == true

# Add Server Manager Remi Channel
- name: Add Server Manager Channel
  command: rhn-channel -u ol-svrmgr -p ol-svrmgr -a -c remi-epel-el7
  when:
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "OracleLinux"
    - add_optional_channel == true

- name: Add Server Manager Channel
  command: rhn-channel -u ol-svrmgr -p ol-svrmgr -a -c remi-epel-el8
  when:
    - ansible_distribution_major_version == "8"
    - ansible_distribution == "OracleLinux"
    - add_optional_channel == true

- name: Add Server Manager Channel
  command: rhn-channel -u ol-svrmgr -p ol-svrmgr -a -c remi-epel-el9
  when:
    - ansible_distribution_major_version == "9"
    - ansible_distribution == "OracleLinux"
    - add_optional_channel == true

#  Add Repo Files
- name: Add Server Manager Repo
  copy:
    src: "files/ol7-svrmgr.repo"
    dest: "/etc/yum.repos.d/ol7-svrmgr.repo"
    owner: root
    group: root
    mode: u=rw, g=r, o=r
  when:
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "OracleLinux"
    - add_repo == true

# Enable Server Manager Repo
- name: Enable Server Manager Repo
  command: yum-config-manager --enable ol7-svrmgr
  when:
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "OracleLinux"
    - add_repo == true

# Add None Server Manager Repo
- name: Add Repo rpm
  command: dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  when:
    - ansible_distribution_major_version == "9"
    - ansible_distribution == "OracleLinux"
    - add_repo == true

- name: Disable the built-in PostgreSQL module
  command: dnf -qy module disable postgresql
  when:
    - ansible_distribution_major_version == "9"
    - ansible_distribution == "OracleLinux"
    - add_repo == true

# Refresh the cache...
# Update yum cache
- name: Update yum cache
  command: yum makecache
  when:
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "OracleLinux"
    - add_channel == true or add_optional_channel == true or add_repo == true

# update dnf cache
- name: Update dnf cache
  command: dnf makecache
  when:
    - ansible_distribution_major_version == "8"
    - ansible_distribution == "OracleLinux"
    - add_channel == true or add_optional_channel == true or add_repo == true

# update dnf cache
- name: Update dnf cache
  command: dnf makecache
  when:
    - ansible_distribution_major_version == "9"
    - ansible_distribution == "OracleLinux"
    - add_channel == true or add_optional_channel == true or add_repo == true

# REMOVE SERVER MANAGER CHANNELS AND REPOS  IF THEY EXIST
# Remove Server Manager Channel
- name: Remove Server Manager Channel
  command: rhn-channel -u ol-svrmgr -p ol-svrmgr -r ol7_x86_64_latest
  when:
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "OracleLinux"
    - remove_channel == true

# Remove Repo
- name: Remove Server Manager Repo
  command: rm -f /etc/yum.repos.d/ol7-svrmgr.repo
  when:
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "OracleLinux"
    - remove_repo == true

# Allways Clean Cache After Removing Channels and Repos to avoid conflicts.
# Clean yum cache
- name: Clean yum cache
  command: yum clean all
  when:
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "OracleLinux"
    - remove_channel == true or remove_repo == true

# Clean dnf cache
- name: Clean dnf cache
  command: dnf clean all
  when:
    - ansible_distribution_major_version == "8"
    - ansible_distribution == "OracleLinux"
    - remove_channel == true or remove_repo == true

# Clean dnf cache
- name: Clean dnf cache
  command: dnf clean all
  when:
    - ansible_distribution_major_version == "9"
    - ansible_distribution == "OracleLinux"
    - remove_channel == true or remove_repo == true