---
- name: Aide
  include_tasks:
    file: aide.yml
    apply:
    tags:
      - aide
- name: Configure SSH
  include_tasks:
    file: ssh.yml
    apply:
    tags:
      - ssh
- name: Configure Sudo
  include_tasks:
    file: sudo.yml
    apply:
    tags:
      - sudo
- name: Configure Systemd
  include_tasks:
    file: systemd.yml
    apply:
    tags:
      - systemd
- name: Users
  include_tasks:
    file: users.yml
    apply:
    tags:
      - users
- name: crontabs
  include_tasks:
    file: cron.yml
    apply:
    tags:
      - crontabs
- name: Logfiles
  include_tasks:
    file: logfiles.yml
    apply:
    tags:
      - logfiles
- name: Configure Network
  include_tasks:
    file: network.yml
    apply:
    tags:
      - network

- name: reload systemd deamon
  systemd:
    daemon_reload: true
