---
- name: Ensure sudo is installed
  package:
   name: sudo
   state: present
   tags:
    - sudo

- name: Ensure sudoers file is configured
  template:
      src: sudoers.j2
      dest: /etc/sudoers
      owner: root
      group: root
      mode: 0440
      tags:
      - sudo

- name: Ensure sudoers.d directory is present
  file:
      path: /etc/sudoers.d
      state: directory
      owner: root
      group: root
      mode: 0755
      tags:
      - sudo

- name: Ensure sudoers.d files are present
  copy:
  src: "{{ item.src }}"
  dest: "{{ item.dest }}"
  owner: root
  group: root
  mode: 0440
  with_items:
        - { src: 'sudoers.d/10-pinot', dest: '/etc/sudoers.d/10-pinot' }
        - { src: 'sudoers.d/10-ansible', dest: '/etc/sudoers.d/10-ansible' }
  tags:
  - sudo
