---
- name: Ensure systemd is installed
  package:
    name: systemd
    state: present
    tags:
    - systemd

- name: Ensure systemd is running
  service:
    name: systemd
    state: started
    enabled: true
    tags:
    - systemd

- name: Ensure systemd is configured
  template:
    src: systemd.j2
    dest: /etc/systemd/system.conf
    owner: root
    group: root
    mode: 0644
    tags:
    - systemd
