---
- name: build yara
  command: /bin/bash "{{ yara_home }}/bootstrap.sh"
  become: true
  when: download_yara.changed
  tags: [yara]

- name: configure yara
  command: /bin/bash -c "{{ yara_home }}/configure"
  become: true
  when: download_yara.changed
  tags: [yara]

- name: run make on yara
  command: /bin/bash -c "{{ yara_home }}make"
  become: true
  when: download_yara.changed
  tags: [yara]

- name: run make instal on yara
  command: /bin/bash -c "{{ yara_home }}make install"
  become: true
  when: download_yara.changed
  tags: [yara]

- name: run make check on yara
  command: /bin/bash -c "{{ yara_home }}make check"
  become: true
  when: download_yara.changed
  tags: [yara]

- name: Add yara to the path
  command: /bin/bash -c "echo '/usr/local/lib' >> /etc/ld.so.conf"
  become: true
  when: download_yara.changed
  tags: [yara]
- name: Run ldconfig
  command: ldconfig

- name: Run yara
  command: yara -v
  tags: [yara]
