# Update OS configuration files

# FIXME: hosts file is not updated. Need to fix this.
#  hostname
# - name: Updating /etc/hosts File on All Cluster Nodes
#   template:
#         src: "templates/hosts.j2"
#         dest: "/etc/hosts"
#         force: true
#         owner: root
#         group: root
#         mode: u=rw,g=r,o=r
#         backup: true

# - name: Set up bash_rc
#   blockinfile:
#     path: /root/.bashrc
#     create: yes
#     backup: true
#     block: |
#        shopt -s histappend histreedit histverify
#        shopt -s no_empty_cmd_completion
#        export HISTCONTROL=ignoreboth:erasedups
#        export HISTTIMEFORMAT="%Y-%m-%d:%T:-> "
#        export HISTIGNORE="pwd:bg:fg:history"
#        export HISTFILE=$HOME/.bash_history
#        export HISTFILESIZE=1000000000
#        export HISTSIZE=10000000

# - name: Source the bashrc file
#   shell: source /root/.bashrc

# Create Directory Structure


- name: reload firewalld deamon
  firewalld:
    daemon_reload: yes

# Cleanup the RAM
# After installation clean the RAM so that we get the required free space.
- name: Clean Ram Cache
  copy:
    content: 3
    dest: /proc/sys/vm/drop_caches
    unsafe_writes: true
  become: true
