---
- name: Job
  # REMOVE THE NEXT 3 LINE IF CALLING FROM ANOTHER MAIN YML
  hosts: all
  gather_facts: true
  become: true

  vars_files:
    - vars/vars.yml

  pre_tasks:
    - name: update all packages
      yum:
        name: '*'
        state: latest

  tasks:
    - debug:
        msg: "Running {{ ansible_play_name }} on {{ inventory_hostname }}"
        verbosity: 1

    - name: check variables
      include_tasks:
        file: tasks/check_vars.yml
        apply:
          tags:
            - check_vars

    - name: Install Default Packages
      include_tasks:
        file: tasks/default_packages.yml
        apply:
          tags:
            - dependencies

    - name: create users
      include_tasks:
        file: tasks/users.yml
        apply:
          tags:
            - users

    - name: download packages
      include_tasks:
        file: tasks/download.yml
        apply:
          tags:
            - download

    - name: install packages
      include_tasks:
        file: tasks/install.yml
        apply:
          tags:
            - install

    - name: configure packages
      include_tasks:
        file: tasks/config.yml
        apply:
          tags:
            - config

  handlers:
    - name: Restart Service <nanme>
      ansible.builtin.service:
        name: systemcld
        state: restarted
