- name: Generate an private key with elliptic curve cryptography (ECC)
  host: hdfsnn01
  community.crypto.openssl_privatekey:
    path: "{{hadoop_home}}/hadoop_ssl_priv.pem"
    owner: root
    group: root
    mode: 0600
    regenerate: full_idempotence
    backup: true
    type: ECC
    curve: secp256r1
    passphrase: changeit

- name: Generate an OpenSSL public key in PEM format
  community.crypto.openssl_publickey:
    path: "{{hadoop_home}}/hadoop_ssl_pub.pem"
    privatekey_content: "{{hadoop_home}}/hadoop_ssl_priv.pem"
    privatekey_passphrase: changeit
    owner: root
    group: root
    mode: 0600
    type: ECC
    curve: secp256r1
    backup: true


- name: create java keystore
  java_keystore:
    name: hadoop
    owner: "{{hdfs_user}}"
    group: "{{hdfs_group}}"
    mode: 0600
    certificate: "{{hadoop_home}}/hadoop_ssl_pub.pem"
    private_key: "{{hadoop_home}}/hadoop_ssl_priv.pem"
    password: changeit
    keystore_type: pkcs12
    keystore_path: "{{hadoop_home}}/keystore.p12"