---
# Ensure core dumps are restricted
# /etc/systemd/coredump.conf
- name: Ensure core dumps are restricted
  command: "{{ item }}"
  become: true
  backup: true
  with_items:
    # Storage=external -> core dumps are stored externally
    # in /var/lib/systemd/coredump/
    - "echo 'Storage=external' >> /etc/systemd/coredump.conf"
    - "echo 'ProcessSizeMax=2G' >> /etc/systemd/coredump.conf"
    - "echo 'ExternalSizeMax=2G' >> /etc/systemd/coredump.conf"
    - "echo 'JournalSizeMax=666M' >> /etc/systemd/coredump.conf"
    - "echo 'MaxUse=2G' >> /etc/systemd/coredump.conf"
    - "echo 'KeepFree=20' >> /etc/systemd/coredump.conf"
    - "echo 'Compress=yes' >> /etc/systemd/coredump.conf"
  tags: [coredump]

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  tags: [coredump]
