---
# Put all kernel settings here
- name: Network Kernel Settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
    backup: true
    with_items:
      - {name: net.ipv4.conf.all.rp_filter, value: 1}
      - {name: net.ipv4.conf.default.rp_filter, value: 1}
      - {name: net.ipv4.conf.all.accept_redirects, value: 0}
      - {name: net.ipv4.conf.default.accept_redirects, value: 0}
      - {name: net.ipv6.conf.all.accept_redirects, value: 0}
      - {name: net.ipv6.conf.default.accept_redirects, value: 0}
      - {name: net.ipv4.route.flush, value: 1}
      - {name: net.ipv6.route.flush, value: 1}

- name: Kenerl Memory and System Settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
    backup: true
    with_items:
      - {name: vm.swappiness, value: 10}
      - {name: vm.dirty_ratio, value: 60}
      - {name: vm.dirty_background_ratio, value: 2}
      - {name: vm.dirty_expire_centisecs, value: 500}
      - {name: vm.dirty_writeback_centisecs, value: 1000}
      - {name: vm.overcommit_memory, value: 2}
      - {name: vm.overcommit_ratio, value: 100}
      - {name: vm.panic_on_oom, value: 0}
      - {name: kernel.panic, value: 10}
      - {name: kernel.randomize_va_space, value: 2}
      - {name: kernel.exec-shield, value: 1}
      - {name: kernel.kptr_restrict, value: 2}
      - {name: kernel.dmesg_restrict, value: 1}
      - {name: kernel.yama.ptrace_scope, value: 1}
      - {name: kernel.unprivileged_bpf_disabled, value: 1}
      - {name: kernel.kexec_load_disabled, value: 1}
      - {name: kernel.perf_event_paranoid, value: 3}

- name: File Limits
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
    backup: true
    with_items:
      - {name: fs.suid_dumpable, value: 0}
