---
- name: Blank Playbook
# Remove the next 3 line if you are calling  from another main.
  hosts: all
  gather_facts: true
  become: true

  vars_files:
    - vars/vars.yml

  pre_tasks:
    # Remove the update task if your main yaml is already doing this , saves on time.
    - name: update all packages
      yum:
        name: '*'
        state: latest

  tasks:
    - name: Runing Play
      debug:
        msg: "Running {{ ansible_play_name }} on {{ inventory_hostname }}"
        verbosity: 1
    - name: Os level
      debug:
        msg: "Running on {{ansible_distribution }} version {{ansible_distribution_major_version}}"
        verbosity: 1

    - name: Install Default Packages
      include_tasks:
        file: tasks/default_packages.yml
        apply:
          tags:
            - dependencies

    - name: Create Users
      include_tasks:
        file: tasks/users.yml
        apply:
          tags:
            - users

    - name: Download Packages (None Package Manager)
      include_tasks:
        file: tasks/download.yml
        apply:
          tags:
            - download

    - name: Install Packages (None Package Manager)
      include_tasks:
        file: tasks/install.yml
        apply:
          tags:
            - install

    - name: Configure Packages (None Package Manager)
      include_tasks:
        file: tasks/config.yml
        apply:
          tags:
            - config

  handlers:
    - name: Restart Service <nanme>
      ansible.builtin.service:
        name: systemcld
        state: restarted
