# Update OS configuration files

# FIXME: hosts file is not updated. Need to fix this.
#  hostname
# - name: Updating /etc/hosts File on All Cluster Nodes
#   template:
#         src: "templates/hosts.j2"
#         dest: "/etc/hosts"
#         force: true
#         owner: root
#         group: root
#         mode: u=rw,g=r,o=r
#         backup: true

# Create Directory Structure
- name: create zookeeper config directory
  file:
    path: /etc/zookeeper/
    state: directory
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: u=rwx,g=rx,o=rx
  become: true
  when: zookeeper_enabled == true

- name: create zookeeper directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: u=rwx,g=rx,o=rx
  become: true
  with_items:
  - "{{ zookeeper_data_dir }}"
  - "{{ zookeeper_data_log_dir }}"
  - "{{ zookeeper_log_dir }}"
  - "{{ zookeeper_pid_dir }}"
  when: zookeeper_user is defined and zookeeper_group is defined and zookeeper_enabled == true

# Setup Appliacation Enviroment Files
- name: Create  Zookeeper myid
  file:
    path: "{{ zookeeper_myid_file }}"
    state: touch
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: u=rw,g=r,o=r
  become: true
  when: zookeeper_user is defined and zookeeper_group is defined and zookeeper_enabled == true

- name: Set up java.sh in /etc/profile.d/
  template:
    src: "files/java.sh"
    dest: "/etc/profile.d/java.sh"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: true


- name: Set up zookeeper.sh in /etc/profile.d
  template:
    src: "files/zookeeper.sh"
    dest: "/etc/profile.d/zookeeper.sh"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: true
  when: zookeeper_enabled == true

# Firewall Configuration Files for OS

- name: setup zookeeper firewall ports
  template:
    src: "files/zookeeper.xml"
    dest: "/usr/lib/firewalld/services"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: true
  when: zookeeper_enabled == true

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
    enabled: true

# Activate Application Specific Firewall Rules.

- name: add zookeeper service to firewalld
  firewalld:
    service: zookeeper
    permanent: true
    state: enabled
    immediate: true
  when: zookeeper_enabled == true

- name: reload firewalld deamon
  firewalld:
    daemon_reload: yes

# Cleanup the RAM
# After installation clean the RAM so that we get the required free space.
- name: Clean Ram Cache
  copy:
    content: 3
    dest: /proc/sys/vm/drop_caches
    unsafe_writes: true
  become: true
