---
# Add Downloads to the list
- name: Install Additional Pacakges
  yum:
   name:
    - scap-security-guide.noarch
  state: present
  become: true
  become_user: root
  when:
    - oscap_enabled == true
  tags: [Oscap Enabled]

- name: Download Yara
  get_url: https://github.com/VirusTotal/yara/archive/refs/tags/v{yara_version}.tar.gz
  dest: /tmp/yara-{yara_version}.tar.gz
  mode: u=rw
  when:
    - yara_enabled == true
  tags: [Yara Enabled]
