---
# Update OS configuration files

# FIXME: hosts file is not updated. Need to fix this.
#  hostname
# - name: Updating /etc/hosts File on All Cluster Nodes
#   template:
#         src: "templates/hosts.j2"
#         dest: "/etc/hosts"
#         force: true
#         owner: root
#         group: root
#         mode: u=rw,g=r,o=r
#         backup: true

- name: Set up bash_rc
  tags: bashrc
  blockinfile:
    path: /root/.bashrc
    create: true
    backup: true
    block: |
      shopt -s histappend histreedit histverify
      shopt -s no_empty_cmd_completion
      export HISTCONTROL=ignoreboth:erasedups
      export HISTTIMEFORMAT="%Y-%m-%d:%T:-> "
      export HISTIGNORE="pwd:bg:fg:history"
      export HISTFILE=$HOME/.bash_history
      export HISTFILESIZE=1000000000
      export HISTSIZE=10000000
  when: bashrc == true

- name: Source the bashrc file
  shell: source /root/.bashrc
  when: bashrc == true

# Create Directory Structure for the Application
- name: create oscap directory
  tags: oscap_dir
  file:
    path: /var/ossec/wodles/oscap
    state: directory
    owner: "{{ root_user }}"
    group: "{{ wazuh_group }}"
    mode: u=rwx,g=rx,o=rx
  become: true
  when: oscap_enabled == true

- name: create oscap content directory
  tags: oscap_content_dir
  file:
    path: /var/ossec/wodles/oscap/content
    state: directory
    owner: "{{ root_user }}"
    group: "{{ wazuh_group }}"
    mode: u=rwx,g=rx,o=rx
  become: true
  when: oscap_enabled == true

- name: Create Yara Rules Directory
  file:
    path: /var/ossec/wodles/yara-rules
    state: directory
    owner: "{{ root_user }}"
    group: "{{ wazuh_group }}"
    mode: u=rwx
  become: true
  when: yara_enabled == true
# Add mount points
# Create dummy files
# Install Additional pckages
- name: Copy Audit Rules
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: u=rw
  with_items:
    - {src: "files/ruleset/audit_rules",
       dest: "/etc/audit/rules.d"}
  when: auditd_overwrite_enabled == true

- name: Run augenrules to complie the audit rules and load them.
  command: augenrules --load
  become: true
  when:  auditd_overwrite_enabled == true

- name: copy default scap content
  tags: scap_content
  copy:
    remote_src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ root_user }}"
    group: "{{ wazuh_group }}"
    mode: u=rwx
  with_items:
    - {src: "/usr/share/xml/scap/ssg/content/",
       dest: "/var/ossec/wodles/oscap/content/"}
  when: scap_overwrite_enabled == true

- name: Copy oscap content
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ root_user }}"
    group: "{{ wazuh_group }}"
    mode: u=rwx
  with_items:
    - {src: files/rulesets/oscap,
       dest: /var/ossec/wodles/oscap/content}
  when: oscap_overwrite_enabled == true

- name: Copy sca content
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ root_user }}"
    group: "{{ wazuh_group }}"
    mode: u=rwx
  with_items:
    - {src: files/rulesets/sca,
       dest: /var/ossec/ruleset/sca}
  when: sca_overwrite_enabled == true

- name: Copy Yara Custom Rules
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ root_user }}"
    group: "{{ wazuh_group }}"
    mode: u=rw
  become: true
  with_items:
    - {src: "files/rulesets/yara",
       dest: "/var/ossec/wodles/yara-rules"}
  when: yara_enabled == true


- name: Copy oscap scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ root_user }}"
    group: "{{ wazuh_group }}"
    mode: u=rwx
  with_items:
    - {src: "files/oscap.py",
      dest: "/var/ossec/wodles/oscap/oscap.py"}
  when: oscap_enabled == true

- name: Copy Oscap Script Template Files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ root_user }}"
    group: "{{ wazuh_group }}"
    mode: u=rw
  with_items:
    - {src: "files/template_oval.xsl",
       dest: "/var/ossec/wodles/oscap/template_oval.xsl"}
    - {src: "files/template_xccdf.xsl",
       dest: "/var/ossec/wodles/oscap/template_xccdf.xsl"}
  when: oscap_enabled == true

# Install Yara
- Name: Remove Previous Yara Directory
  shell:
      cmd: /bin/rm -rf yara*
      chdir: /usr/local/bin/
  args:
    executable: /bin/bash
  become: true
  when: yara_enabled == true

- name: Install Yara
  tags: yara_install
  shell:
      cmd: /bin/tar -xvf /tmp/yara-{{yara_version}}.tar.gz -C  /usr/local/bin/
  args:
    executable: /bin/bash
  become: true
  when: yara_enabled == true

- name: Build Yara bootstrap
  shell:
      cmd: bootstrap.sh
      chdir: /usr/local/bin/yara-{{yara_version}}
  args:
    executable: /bin/bash
  become: true
  when: yara_enabled == true

- name: Build Yara configure
  shell:
      cmd: configure
      chdir: /usr/local/bin/yara-{{yara_version}}
  args:
    executable: /bin/bash
  become: true
  when: yara_enabled == true

- name: Build Yara make
  shell:
      cmd: make
      chdir: /usr/local/bin/yara-{{yara_version}}
  args:
    executable: /bin/bash
  become: true
  when: yara_enabled == true

- name: Build Yara make install
  shell:
       cmd: make install
  args:
    executable: /bin/bash
  become: true
  when: yara_enabled == true

- name: Ld Yara Package
  shell:
      cmd: echo /usr/local/lib > /etc/ld.so.conf && ldconfig
  args:
    executable: /bin/bash
  become: true
  when: yara_enabled == true
# Set Premissions
# Remove temp files
